In [499]:
import pandas as pd

In [501]:
df1=pd.read_csv('customers_info.csv')

In [503]:
df2=pd.read_csv('account_info.csv')

In [505]:
df1.head(10)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary
0,15634602,Hargrave,619,FRA,Female,42.0,2,"€ 1,01,348.88"
1,15647311,Hill,608,Spain,Female,41.0,1,"€ 1,12,542.58"
2,15619304,Onio,502,French,Female,42.0,8,"€ 1,13,931.57"
3,15701354,Boni,699,FRA,Female,39.0,1,"€ 93,826.63"
4,15737888,Mitchell,850,Spain,Female,43.0,2,"€ 79,084.10"
5,15574012,Chu,645,Spain,Male,44.0,8,"€ 1,49,756.71"
6,15592531,Bartlett,822,France,Male,50.0,7,"€ 10,062.80"
7,15656148,Obinna,376,Germany,Female,29.0,4,"€ 1,19,346.88"
8,15792365,He,501,French,Male,44.0,4,"€ 74,940.50"
9,15592389,H?,684,France,Male,27.0,2,"€ 71,725.73"

In [507]:
df2.head(10)

,CustomerId,Balance,NumOfProducts,HasCrCard,Tenure,IsActiveMember,Exited
0,15634602,€ 0.00,1,Yes,2,Yes,1
1,15634602,€ 0.00,1,Yes,2,Yes,1
2,15647311,"€ 83,807.86",1,Yes,1,Yes,0
3,15619304,"€ 1,59,660.80",3,No,8,No,1
4,15701354,€ 0.00,2,No,1,No,0
5,15737888,"€ 1,25,510.82",1,Yes,2,Yes,0
6,15574012,"€ 1,13,755.78",2,No,8,No,1
7,15592531,€ 0.00,2,Yes,7,Yes,0
8,15656148,"€ 1,15,046.74",4,No,4,No,1
9,15792365,"€ 1,42,051.07",2,Yes,4,Yes,0

In [509]:
df1.shape,df2.shape

((10001, 8), (10002, 7))

In [511]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10001 non-null  int64
 1   Surname          9998 non-null   object
 2   CreditScore      10001 non-null  int64
 3   Geography        10001 non-null  object
 4   Gender           10001 non-null  object
 5   Age              9998 non-null   float64
 6   Tenure           10001 non-null  int64
 7   EstimatedSalary  10001 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 625.2+ KB

In [513]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerId      10002 non-null  int64
 1   Balance         10002 non-null  object
 2   NumOfProducts   10002 non-null  int64
 3   HasCrCard       10002 non-null  object
 4   Tenure          10002 non-null  int64
 5   IsActiveMember  10002 non-null  object
 6   Exited          10002 non-null  int64
dtypes: int64(4), object(3)
memory usage: 547.1+ KB

In [515]:
df1['EstimatedSalary'].unique()[:10]

array(['€ 1,01,348.88', '€ 1,12,542.58', '€ 1,13,931.57', '€ 93,826.63',
       '€ 79,084.10', '€ 1,49,756.71', '€ 10,062.80', '€ 1,19,346.88',
       '€ 74,940.50', '€ 71,725.73'], dtype=object)

In [517]:
df1["EstimatedSalary"] = (
    df1["EstimatedSalary"]
    .str.replace("€", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace("- ", "-", regex=False)
    .str.strip()
)

df1["EstimatedSalary"] = df1["EstimatedSalary"].astype(float)

In [519]:
df1['EstimatedSalary'].unique()[:10]

array([101348.88, 112542.58, 113931.57,  93826.63,  79084.1 , 149756.71,
        10062.8 , 119346.88,  74940.5 ,  71725.73])

In [521]:
df2['Balance'].unique()[:10]

array(['€ 0.00', '€ 83,807.86', '€ 1,59,660.80', '€ 1,25,510.82',
       '€ 1,13,755.78', '€ 1,15,046.74', '€ 1,42,051.07', '€ 1,34,603.88',
       '€ 1,02,016.72', '€ 1,43,129.41'], dtype=object)

In [523]:
df2["Balance"] = (
    df2["Balance"]
    .str.replace("€", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace("- ", "-", regex=False)
    .str.strip()
)

df2["Balance"] = pd.to_numeric(df2["Balance"], errors="coerce")

In [525]:
df2['Balance'].unique()[:10]

array([     0.  ,  83807.86, 159660.8 , 125510.82, 113755.78, 115046.74,
       142051.07, 134603.88, 102016.72, 143129.41])

In [527]:
df1.duplicated().sum()

1

In [529]:
df2.duplicated().sum()

2

In [531]:
df1[df1.duplicated(keep=False)]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary
9999,15628319,Walker,792,French,Female,28.0,4,38190.78
10000,15628319,Walker,792,French,Female,28.0,4,38190.78

In [533]:
df2[df2.duplicated(keep=False)]

,CustomerId,Balance,NumOfProducts,HasCrCard,Tenure,IsActiveMember,Exited
0,15634602,0.00,1,Yes,2,Yes,1
1,15634602,0.00,1,Yes,2,Yes,1
10000,15628319,130142.79,1,No,4,No,0
10001,15628319,130142.79,1,No,4,No,0

In [535]:
df1=df1.drop_duplicates()

In [537]:
df2=df2.drop_duplicates()

In [539]:
df1.duplicated().sum()

0

In [541]:
df2.duplicated().sum()

0

In [543]:
df1.isnull().sum()

CustomerId         0
Surname            3
CreditScore        0
Geography          0
Gender             0
Age                3
Tenure             0
EstimatedSalary    0
dtype: int64

In [545]:
df2.isnull().sum()

CustomerId        0
Balance           0
NumOfProducts     0
HasCrCard         0
Tenure            0
IsActiveMember    0
Exited            0
dtype: int64

In [547]:
df1=df1.drop("Surname",axis=1)

In [549]:
df1["Age"] = df1["Age"].fillna(df1["Age"].median())

In [551]:
df1.isnull().sum()

CustomerId         0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
EstimatedSalary    0
dtype: int64

In [553]:
df1.columns = df1.columns.str.replace('([a-z])([A-Z])', r'\1_\2', regex=True).str.lower()

In [555]:
df1.columns

Index(['customer_id', 'credit_score', 'geography', 'gender', 'age', 'tenure',
       'estimated_salary'],
      dtype='object')

In [557]:
df2.columns = df2.columns.str.replace('([a-z])([A-Z])', r'\1_\2', regex=True).str.lower()

In [559]:
df2.columns

Index(['customer_id', 'balance', 'num_of_products', 'has_cr_card', 'tenure',
       'is_active_member', 'exited'],
      dtype='object')

In [561]:
df2['churn_status'] = df2['exited'].map({1: 'Churned', 0: 'Retained'})

In [563]:
df2.head(5)

,customer_id,balance,num_of_products,has_cr_card,tenure,is_active_member,exited,churn_status
0,15634602,0.00,1,Yes,2,Yes,1,Churned
2,15647311,83807.86,1,Yes,1,Yes,0,Retained
3,15619304,159660.80,3,No,8,No,1,Churned
4,15701354,0.00,2,No,1,No,0,Retained
5,15737888,125510.82,1,Yes,2,Yes,0,Retained

In [565]:
df1['geography'] = df1['geography'].replace('FRA', 'France')

In [567]:
df = df1.merge(df2, on='customer_id', how='left')

In [569]:
df.head(10)

,customer_id,credit_score,geography,gender,age,tenure_x,estimated_salary,balance,num_of_products,has_cr_card,tenure_y,is_active_member,exited,churn_status
0,15634602,619,France,Female,42.0,2,101348.88,0.00,1,Yes,2,Yes,1,Churned
1,15647311,608,Spain,Female,41.0,1,112542.58,83807.86,1,Yes,1,Yes,0,Retained
2,15619304,502,French,Female,42.0,8,113931.57,159660.80,3,No,8,No,1,Churned
3,15701354,699,France,Female,39.0,1,93826.63,0.00,2,No,1,No,0,Retained
4,15737888,850,Spain,Female,43.0,2,79084.10,125510.82,1,Yes,2,Yes,0,Retained
5,15574012,645,Spain,Male,44.0,8,149756.71,113755.78,2,No,8,No,1,Churned
6,15592531,822,France,Male,50.0,7,10062.80,0.00,2,Yes,7,Yes,0,Retained
7,15656148,376,Germany,Female,29.0,4,119346.88,115046.74,4,No,4,No,1,Churned
8,15792365,501,French,Male,44.0,4,74940.50,142051.07,2,Yes,4,Yes,0,Retained
9,15592389,684,France,Male,27.0,2,71725.73,134603.88,1,Yes,2,Yes,0,Retained

In [571]:
df = df.drop('tenure_y',axis=1)

In [573]:
df = df.rename(columns={'tenure_x': 'tenure'})

In [575]:
df.head(5)

,customer_id,credit_score,geography,gender,age,tenure,estimated_salary,balance,num_of_products,has_cr_card,is_active_member,exited,churn_status
0,15634602,619,France,Female,42.0,2,101348.88,0.00,1,Yes,Yes,1,Churned
1,15647311,608,Spain,Female,41.0,1,112542.58,83807.86,1,Yes,Yes,0,Retained
2,15619304,502,French,Female,42.0,8,113931.57,159660.80,3,No,No,1,Churned
3,15701354,699,France,Female,39.0,1,93826.63,0.00,2,No,No,0,Retained
4,15737888,850,Spain,Female,43.0,2,79084.10,125510.82,1,Yes,Yes,0,Retained

In [577]:
df["age_group"] = pd.cut(
    df["age"],
    bins=[18, 30, 45, 60, 100],
    labels=["18-30", "31-45", "46-60", "60+"],
    include_lowest=True
)

In [579]:
df["credit_score_group"] = pd.cut(
    df["credit_score"],
    bins=[0, 600, 800, float("inf")],
    labels=["0–599", "600–799", "800+"],
    right=False
)

In [581]:
df.head(5)

,customer_id,credit_score,geography,gender,age,tenure,estimated_salary,balance,num_of_products,has_cr_card,is_active_member,exited,churn_status,age_group,credit_score_group
0,15634602,619,France,Female,42.0,2,101348.88,0.00,1,Yes,Yes,1,Churned,31-45,600–799
1,15647311,608,Spain,Female,41.0,1,112542.58,83807.86,1,Yes,Yes,0,Retained,31-45,600–799
2,15619304,502,French,Female,42.0,8,113931.57,159660.80,3,No,No,1,Churned,31-45,0–599
3,15701354,699,France,Female,39.0,1,93826.63,0.00,2,No,No,0,Retained,31-45,600–799
4,15737888,850,Spain,Female,43.0,2,79084.10,125510.82,1,Yes,Yes,0,Retained,31-45,800+

In [583]:
df['geography'] = df['geography'].replace('FRA', 'France')

In [585]:
df = df.rename(columns={'geography': 'country'})

In [587]:
df.head(5)

,customer_id,credit_score,country,gender,age,tenure,estimated_salary,balance,num_of_products,has_cr_card,is_active_member,exited,churn_status,age_group,credit_score_group
0,15634602,619,France,Female,42.0,2,101348.88,0.00,1,Yes,Yes,1,Churned,31-45,600–799
1,15647311,608,Spain,Female,41.0,1,112542.58,83807.86,1,Yes,Yes,0,Retained,31-45,600–799
2,15619304,502,French,Female,42.0,8,113931.57,159660.80,3,No,No,1,Churned,31-45,0–599
3,15701354,699,France,Female,39.0,1,93826.63,0.00,2,No,No,0,Retained,31-45,600–799
4,15737888,850,Spain,Female,43.0,2,79084.10,125510.82,1,Yes,Yes,0,Retained,31-45,800+

In [589]:
!pip install mysql-connector-python sqlalchemy

Requirement already satisfied: mysql-connector-python in c:\users\shais\anaconda3\lib\site-packages (26.7.0)
Requirement already satisfied: sqlalchemy in c:\users\shais\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shais\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\shais\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [590]:
from sqlalchemy import create_engine
from getpass import getpass

# MySQL details
username = "root"
password = getpass("Enter your MySQL password: ")
host = "localhost"
port = "3306"
database = "bank_customer_churn"

# Create connection
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Table name
table_name = "bank_churn"

# Load DataFrame into MySQL
df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Enter your MySQL password:  ········

Data successfully loaded into table 'bank_churn' in database 'bank_customer_churn'.